/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars;

import com.simonbaars.GoLDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoLDSLStandaloneSetup extends GoLDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new GoLDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
