/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars;

import com.simonbaars.AbstractGoLDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoLDSLRuntimeModule extends AbstractGoLDSLRuntimeModule {
}
