/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.ide;

import com.simonbaars.ide.AbstractGoLDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GoLDSLIdeModule extends AbstractGoLDSLIdeModule {
}
