/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.simonbaars.GoLDSLRuntimeModule;
import com.simonbaars.GoLDSLStandaloneSetup;
import com.simonbaars.ide.GoLDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GoLDSLIdeSetup extends GoLDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GoLDSLRuntimeModule _goLDSLRuntimeModule = new GoLDSLRuntimeModule();
    GoLDSLIdeModule _goLDSLIdeModule = new GoLDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_goLDSLRuntimeModule, _goLDSLIdeModule));
  }
}
