/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGoLDSLScopeProvider extends DelegatingScopeProvider {
}
