/**
 * generated by Xtext 2.19.0
 */
package persons.tasks;

import persons.tasks.AbstractTaskDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaskDSLRuntimeModule extends AbstractTaskDSLRuntimeModule {
}
