/**
 * generated by Xtext 2.19.0
 */
package persons.tasks.scoping;

import com.google.common.base.Objects;
import java.util.Collection;
import java.util.LinkedList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import persons.tasks.scoping.AbstractTaskDSLScopeProvider;
import persons.tasks.taskDSL.ProjectUse;
import persons.tasks.taskDSL.Task;
import persons.tasks.taskDSL.TaskDSLPackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TaskDSLScopeProvider extends AbstractTaskDSLScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    if (((context instanceof ProjectUse) && 
      Objects.equal(reference, TaskDSLPackage.Literals.PROJECT_USE__PROJECT))) {
      return this.getScopeProjectUseProject(((ProjectUse) context));
    }
    return super.getScope(context, reference);
  }
  
  private IScope getScopeProjectUseProject(final ProjectUse projectUse) {
    EObject context = projectUse;
    while ((!((context == null) || (context instanceof Task)))) {
      context = context.eContainer();
    }
    Task runningTask = ((Task) context);
    IScope scope = IScope.NULLSCOPE;
    Collection<Task> visited = new LinkedList<Task>();
    while (((runningTask != null) && (!visited.contains(runningTask)))) {
      {
        visited.add(runningTask);
        scope = Scopes.scopeFor(runningTask.getProjects(), scope);
        runningTask = runningTask.getExtends();
      }
    }
    return scope;
  }
}
