/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Board</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.Board#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getBoard()
 * @model
 * @generated
 */
public interface Board extends EObject
{
  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference.
   * @see #setObjects(Objects)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getBoard_Objects()
   * @model containment="true"
   * @generated
   */
  Objects getObjects();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.Board#getObjects <em>Objects</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objects</em>' containment reference.
   * @see #getObjects()
   * @generated
   */
  void setObjects(Objects value);

} // Board
