/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bounded Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.BoundedRange#getLowerBound <em>Lower Bound</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.BoundedRange#getHigherBound <em>Higher Bound</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getBoundedRange()
 * @model
 * @generated
 */
public interface BoundedRange extends EObject
{
  /**
   * Returns the value of the '<em><b>Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower Bound</em>' attribute.
   * @see #setLowerBound(int)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getBoundedRange_LowerBound()
   * @model
   * @generated
   */
  int getLowerBound();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.BoundedRange#getLowerBound <em>Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower Bound</em>' attribute.
   * @see #getLowerBound()
   * @generated
   */
  void setLowerBound(int value);

  /**
   * Returns the value of the '<em><b>Higher Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Higher Bound</em>' attribute.
   * @see #setHigherBound(int)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getBoundedRange_HigherBound()
   * @model
   * @generated
   */
  int getHigherBound();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.BoundedRange#getHigherBound <em>Higher Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Higher Bound</em>' attribute.
   * @see #getHigherBound()
   * @generated
   */
  void setHigherBound(int value);

} // BoundedRange
