/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell Def</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getCellDef()
 * @model
 * @generated
 */
public interface CellDef extends EObject
{
} // CellDef
