/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.ConditionRule#getNumber <em>Number</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.ConditionRule#getRange <em>Range</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.ConditionRule#getAlive <em>Alive</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.ConditionRule#getDead <em>Dead</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getConditionRule()
 * @model
 * @generated
 */
public interface ConditionRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getConditionRule_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ConditionRule#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(Range)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getConditionRule_Range()
   * @model containment="true"
   * @generated
   */
  Range getRange();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ConditionRule#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(Range value);

  /**
   * Returns the value of the '<em><b>Alive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alive</em>' attribute.
   * @see #setAlive(String)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getConditionRule_Alive()
   * @model
   * @generated
   */
  String getAlive();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ConditionRule#getAlive <em>Alive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alive</em>' attribute.
   * @see #getAlive()
   * @generated
   */
  void setAlive(String value);

  /**
   * Returns the value of the '<em><b>Dead</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dead</em>' attribute.
   * @see #setDead(String)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getConditionRule_Dead()
   * @model
   * @generated
   */
  String getDead();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ConditionRule#getDead <em>Dead</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dead</em>' attribute.
   * @see #getDead()
   * @generated
   */
  void setDead(String value);

} // ConditionRule
