/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.DSL#getBoard <em>Board</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.DSL#getRules <em>Rules</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.DSL#getShapes <em>Shapes</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getDSL()
 * @model
 * @generated
 */
public interface DSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Board</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Board</em>' containment reference.
   * @see #setBoard(Board)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getDSL_Board()
   * @model containment="true"
   * @generated
   */
  Board getBoard();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.DSL#getBoard <em>Board</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Board</em>' containment reference.
   * @see #getBoard()
   * @generated
   */
  void setBoard(Board value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getDSL_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

  /**
   * Returns the value of the '<em><b>Shapes</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.ShapeDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shapes</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getDSL_Shapes()
   * @model containment="true"
   * @generated
   */
  EList<ShapeDef> getShapes();

} // DSL
