/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.simonbaars.goLDSL.GoLDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GoLDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "goLDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.simonbaars.com/GoLDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "goLDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GoLDSLPackage eINSTANCE = com.simonbaars.goLDSL.impl.GoLDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.DSLImpl <em>DSL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.DSLImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getDSL()
   * @generated
   */
  int DSL = 0;

  /**
   * The feature id for the '<em><b>Board</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__BOARD = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__RULES = 1;

  /**
   * The feature id for the '<em><b>Shapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__SHAPES = 2;

  /**
   * The number of structural features of the '<em>DSL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.BoardImpl <em>Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.BoardImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoard()
   * @generated
   */
  int BOARD = 1;

  /**
   * The number of structural features of the '<em>Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ObjectsImpl <em>Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ObjectsImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getObjects()
   * @generated
   */
  int OBJECTS = 2;

  /**
   * The feature id for the '<em><b>Shapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTS__SHAPES = BOARD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cell</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTS__CELL = BOARD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTS__CELLS = BOARD_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Grids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTS__GRIDS = BOARD_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTS_FEATURE_COUNT = BOARD_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ShapeDefImpl <em>Shape Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ShapeDefImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getShapeDef()
   * @generated
   */
  int SHAPE_DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Offset</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_DEF__OFFSET = 1;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_DEF__OBJECTS = 2;

  /**
   * The number of structural features of the '<em>Shape Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_DEF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.CellsImpl <em>Cells</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.CellsImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCells()
   * @generated
   */
  int CELLS = 5;

  /**
   * The number of structural features of the '<em>Cells</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELLS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.CellPairsImpl <em>Cell Pairs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.CellPairsImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCellPairs()
   * @generated
   */
  int CELL_PAIRS = 4;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_PAIRS__CELLS = CELLS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cell Pairs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_PAIRS_FEATURE_COUNT = CELLS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.CellDefImpl <em>Cell Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.CellDefImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCellDef()
   * @generated
   */
  int CELL_DEF = 6;

  /**
   * The number of structural features of the '<em>Cell Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_DEF_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ShapeRefImpl <em>Shape Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ShapeRefImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getShapeRef()
   * @generated
   */
  int SHAPE_REF = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_REF__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_REF__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_REF__Y = 2;

  /**
   * The number of structural features of the '<em>Shape Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_REF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.CellImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 8;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__X = CELL_DEF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__Y = CELL_DEF_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = CELL_DEF_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.RuleImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTION = 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ActionImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 10;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ConditionImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 11;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ConditionRuleImpl <em>Condition Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ConditionRuleImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getConditionRule()
   * @generated
   */
  int CONDITION_RULE = 12;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULE__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULE__RANGE = 1;

  /**
   * The feature id for the '<em><b>Alive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULE__ALIVE = 2;

  /**
   * The feature id for the '<em><b>Dead</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULE__DEAD = 3;

  /**
   * The number of structural features of the '<em>Condition Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.ConditionRulesImpl <em>Condition Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.ConditionRulesImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getConditionRules()
   * @generated
   */
  int CONDITION_RULES = 13;

  /**
   * The feature id for the '<em><b>Rule1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULES__RULE1 = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULES__OPERATOR = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rule2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULES__RULE2 = CONDITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Condition Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_RULES_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.RangeImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRange()
   * @generated
   */
  int RANGE = 14;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.BoundedRangeImpl <em>Bounded Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.BoundedRangeImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoundedRange()
   * @generated
   */
  int BOUNDED_RANGE = 15;

  /**
   * The feature id for the '<em><b>Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUNDED_RANGE__LOWER_BOUND = RANGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Higher Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUNDED_RANGE__HIGHER_BOUND = RANGE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bounded Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUNDED_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.LeftUnboundedRangeImpl <em>Left Unbounded Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.LeftUnboundedRangeImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getLeftUnboundedRange()
   * @generated
   */
  int LEFT_UNBOUNDED_RANGE = 16;

  /**
   * The feature id for the '<em><b>Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_UNBOUNDED_RANGE__LOWER_BOUND = RANGE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left Unbounded Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_UNBOUNDED_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.RightUnboundedRangeImpl <em>Right Unbounded Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.RightUnboundedRangeImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRightUnboundedRange()
   * @generated
   */
  int RIGHT_UNBOUNDED_RANGE = 17;

  /**
   * The feature id for the '<em><b>Higher Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_UNBOUNDED_RANGE__HIGHER_BOUND = RANGE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right Unbounded Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_UNBOUNDED_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.GridImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getGrid()
   * @generated
   */
  int GRID = 18;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__SIZE = 0;

  /**
   * The feature id for the '<em><b>Parts</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__PARTS = 1;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.OffsetImpl <em>Offset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.OffsetImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getOffset()
   * @generated
   */
  int OFFSET = 19;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OFFSET__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OFFSET__Y = 1;

  /**
   * The number of structural features of the '<em>Offset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OFFSET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.impl.SizeImpl <em>Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.impl.SizeImpl
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getSize()
   * @generated
   */
  int SIZE = 20;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__WIDTH = 0;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE__HEIGHT = 1;

  /**
   * The number of structural features of the '<em>Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.BoolOperator <em>Bool Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.BoolOperator
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoolOperator()
   * @generated
   */
  int BOOL_OPERATOR = 21;

  /**
   * The meta object id for the '{@link com.simonbaars.goLDSL.GridPart <em>Grid Part</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.goLDSL.GridPart
   * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getGridPart()
   * @generated
   */
  int GRID_PART = 22;


  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.DSL <em>DSL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DSL</em>'.
   * @see com.simonbaars.goLDSL.DSL
   * @generated
   */
  EClass getDSL();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.DSL#getBoard <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Board</em>'.
   * @see com.simonbaars.goLDSL.DSL#getBoard()
   * @see #getDSL()
   * @generated
   */
  EReference getDSL_Board();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.DSL#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see com.simonbaars.goLDSL.DSL#getRules()
   * @see #getDSL()
   * @generated
   */
  EReference getDSL_Rules();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.DSL#getShapes <em>Shapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shapes</em>'.
   * @see com.simonbaars.goLDSL.DSL#getShapes()
   * @see #getDSL()
   * @generated
   */
  EReference getDSL_Shapes();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Board <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board</em>'.
   * @see com.simonbaars.goLDSL.Board
   * @generated
   */
  EClass getBoard();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Objects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objects</em>'.
   * @see com.simonbaars.goLDSL.Objects
   * @generated
   */
  EClass getObjects();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.Objects#getShapes <em>Shapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shapes</em>'.
   * @see com.simonbaars.goLDSL.Objects#getShapes()
   * @see #getObjects()
   * @generated
   */
  EReference getObjects_Shapes();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.Objects#getCell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cell</em>'.
   * @see com.simonbaars.goLDSL.Objects#getCell()
   * @see #getObjects()
   * @generated
   */
  EReference getObjects_Cell();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.Objects#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see com.simonbaars.goLDSL.Objects#getCells()
   * @see #getObjects()
   * @generated
   */
  EReference getObjects_Cells();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.Objects#getGrids <em>Grids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Grids</em>'.
   * @see com.simonbaars.goLDSL.Objects#getGrids()
   * @see #getObjects()
   * @generated
   */
  EReference getObjects_Grids();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.ShapeDef <em>Shape Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shape Def</em>'.
   * @see com.simonbaars.goLDSL.ShapeDef
   * @generated
   */
  EClass getShapeDef();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ShapeDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.simonbaars.goLDSL.ShapeDef#getName()
   * @see #getShapeDef()
   * @generated
   */
  EAttribute getShapeDef_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.ShapeDef#getOffset <em>Offset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Offset</em>'.
   * @see com.simonbaars.goLDSL.ShapeDef#getOffset()
   * @see #getShapeDef()
   * @generated
   */
  EReference getShapeDef_Offset();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.ShapeDef#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Objects</em>'.
   * @see com.simonbaars.goLDSL.ShapeDef#getObjects()
   * @see #getShapeDef()
   * @generated
   */
  EReference getShapeDef_Objects();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.CellPairs <em>Cell Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Pairs</em>'.
   * @see com.simonbaars.goLDSL.CellPairs
   * @generated
   */
  EClass getCellPairs();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.goLDSL.CellPairs#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see com.simonbaars.goLDSL.CellPairs#getCells()
   * @see #getCellPairs()
   * @generated
   */
  EReference getCellPairs_Cells();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Cells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cells</em>'.
   * @see com.simonbaars.goLDSL.Cells
   * @generated
   */
  EClass getCells();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.CellDef <em>Cell Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Def</em>'.
   * @see com.simonbaars.goLDSL.CellDef
   * @generated
   */
  EClass getCellDef();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.ShapeRef <em>Shape Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shape Ref</em>'.
   * @see com.simonbaars.goLDSL.ShapeRef
   * @generated
   */
  EClass getShapeRef();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ShapeRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.simonbaars.goLDSL.ShapeRef#getName()
   * @see #getShapeRef()
   * @generated
   */
  EAttribute getShapeRef_Name();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ShapeRef#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.simonbaars.goLDSL.ShapeRef#getX()
   * @see #getShapeRef()
   * @generated
   */
  EAttribute getShapeRef_X();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ShapeRef#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.simonbaars.goLDSL.ShapeRef#getY()
   * @see #getShapeRef()
   * @generated
   */
  EAttribute getShapeRef_Y();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see com.simonbaars.goLDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Cell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.simonbaars.goLDSL.Cell#getX()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_X();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Cell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.simonbaars.goLDSL.Cell#getY()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Y();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see com.simonbaars.goLDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see com.simonbaars.goLDSL.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Condition();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.Rule#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see com.simonbaars.goLDSL.Rule#getAction()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Action();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see com.simonbaars.goLDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see com.simonbaars.goLDSL.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.ConditionRule <em>Condition Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition Rule</em>'.
   * @see com.simonbaars.goLDSL.ConditionRule
   * @generated
   */
  EClass getConditionRule();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ConditionRule#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see com.simonbaars.goLDSL.ConditionRule#getNumber()
   * @see #getConditionRule()
   * @generated
   */
  EAttribute getConditionRule_Number();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.ConditionRule#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see com.simonbaars.goLDSL.ConditionRule#getRange()
   * @see #getConditionRule()
   * @generated
   */
  EReference getConditionRule_Range();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ConditionRule#getAlive <em>Alive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alive</em>'.
   * @see com.simonbaars.goLDSL.ConditionRule#getAlive()
   * @see #getConditionRule()
   * @generated
   */
  EAttribute getConditionRule_Alive();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ConditionRule#getDead <em>Dead</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dead</em>'.
   * @see com.simonbaars.goLDSL.ConditionRule#getDead()
   * @see #getConditionRule()
   * @generated
   */
  EAttribute getConditionRule_Dead();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.ConditionRules <em>Condition Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition Rules</em>'.
   * @see com.simonbaars.goLDSL.ConditionRules
   * @generated
   */
  EClass getConditionRules();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.ConditionRules#getRule1 <em>Rule1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule1</em>'.
   * @see com.simonbaars.goLDSL.ConditionRules#getRule1()
   * @see #getConditionRules()
   * @generated
   */
  EReference getConditionRules_Rule1();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.ConditionRules#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see com.simonbaars.goLDSL.ConditionRules#getOperator()
   * @see #getConditionRules()
   * @generated
   */
  EAttribute getConditionRules_Operator();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.ConditionRules#getRule2 <em>Rule2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule2</em>'.
   * @see com.simonbaars.goLDSL.ConditionRules#getRule2()
   * @see #getConditionRules()
   * @generated
   */
  EReference getConditionRules_Rule2();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see com.simonbaars.goLDSL.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.BoundedRange <em>Bounded Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bounded Range</em>'.
   * @see com.simonbaars.goLDSL.BoundedRange
   * @generated
   */
  EClass getBoundedRange();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.BoundedRange#getLowerBound <em>Lower Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lower Bound</em>'.
   * @see com.simonbaars.goLDSL.BoundedRange#getLowerBound()
   * @see #getBoundedRange()
   * @generated
   */
  EAttribute getBoundedRange_LowerBound();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.BoundedRange#getHigherBound <em>Higher Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Higher Bound</em>'.
   * @see com.simonbaars.goLDSL.BoundedRange#getHigherBound()
   * @see #getBoundedRange()
   * @generated
   */
  EAttribute getBoundedRange_HigherBound();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.LeftUnboundedRange <em>Left Unbounded Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left Unbounded Range</em>'.
   * @see com.simonbaars.goLDSL.LeftUnboundedRange
   * @generated
   */
  EClass getLeftUnboundedRange();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.LeftUnboundedRange#getLowerBound <em>Lower Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lower Bound</em>'.
   * @see com.simonbaars.goLDSL.LeftUnboundedRange#getLowerBound()
   * @see #getLeftUnboundedRange()
   * @generated
   */
  EAttribute getLeftUnboundedRange_LowerBound();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.RightUnboundedRange <em>Right Unbounded Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right Unbounded Range</em>'.
   * @see com.simonbaars.goLDSL.RightUnboundedRange
   * @generated
   */
  EClass getRightUnboundedRange();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.RightUnboundedRange#getHigherBound <em>Higher Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Higher Bound</em>'.
   * @see com.simonbaars.goLDSL.RightUnboundedRange#getHigherBound()
   * @see #getRightUnboundedRange()
   * @generated
   */
  EAttribute getRightUnboundedRange_HigherBound();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see com.simonbaars.goLDSL.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.goLDSL.Grid#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see com.simonbaars.goLDSL.Grid#getSize()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Size();

  /**
   * Returns the meta object for the attribute list '{@link com.simonbaars.goLDSL.Grid#getParts <em>Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parts</em>'.
   * @see com.simonbaars.goLDSL.Grid#getParts()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_Parts();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Offset <em>Offset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Offset</em>'.
   * @see com.simonbaars.goLDSL.Offset
   * @generated
   */
  EClass getOffset();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Offset#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.simonbaars.goLDSL.Offset#getX()
   * @see #getOffset()
   * @generated
   */
  EAttribute getOffset_X();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Offset#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.simonbaars.goLDSL.Offset#getY()
   * @see #getOffset()
   * @generated
   */
  EAttribute getOffset_Y();

  /**
   * Returns the meta object for class '{@link com.simonbaars.goLDSL.Size <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size</em>'.
   * @see com.simonbaars.goLDSL.Size
   * @generated
   */
  EClass getSize();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Size#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see com.simonbaars.goLDSL.Size#getWidth()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Width();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.goLDSL.Size#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see com.simonbaars.goLDSL.Size#getHeight()
   * @see #getSize()
   * @generated
   */
  EAttribute getSize_Height();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.goLDSL.BoolOperator <em>Bool Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool Operator</em>'.
   * @see com.simonbaars.goLDSL.BoolOperator
   * @generated
   */
  EEnum getBoolOperator();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.goLDSL.GridPart <em>Grid Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Grid Part</em>'.
   * @see com.simonbaars.goLDSL.GridPart
   * @generated
   */
  EEnum getGridPart();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GoLDSLFactory getGoLDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.DSLImpl <em>DSL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.DSLImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getDSL()
     * @generated
     */
    EClass DSL = eINSTANCE.getDSL();

    /**
     * The meta object literal for the '<em><b>Board</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__BOARD = eINSTANCE.getDSL_Board();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__RULES = eINSTANCE.getDSL_Rules();

    /**
     * The meta object literal for the '<em><b>Shapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__SHAPES = eINSTANCE.getDSL_Shapes();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.BoardImpl <em>Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.BoardImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoard()
     * @generated
     */
    EClass BOARD = eINSTANCE.getBoard();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ObjectsImpl <em>Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ObjectsImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getObjects()
     * @generated
     */
    EClass OBJECTS = eINSTANCE.getObjects();

    /**
     * The meta object literal for the '<em><b>Shapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTS__SHAPES = eINSTANCE.getObjects_Shapes();

    /**
     * The meta object literal for the '<em><b>Cell</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTS__CELL = eINSTANCE.getObjects_Cell();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTS__CELLS = eINSTANCE.getObjects_Cells();

    /**
     * The meta object literal for the '<em><b>Grids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTS__GRIDS = eINSTANCE.getObjects_Grids();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ShapeDefImpl <em>Shape Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ShapeDefImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getShapeDef()
     * @generated
     */
    EClass SHAPE_DEF = eINSTANCE.getShapeDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHAPE_DEF__NAME = eINSTANCE.getShapeDef_Name();

    /**
     * The meta object literal for the '<em><b>Offset</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHAPE_DEF__OFFSET = eINSTANCE.getShapeDef_Offset();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHAPE_DEF__OBJECTS = eINSTANCE.getShapeDef_Objects();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.CellPairsImpl <em>Cell Pairs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.CellPairsImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCellPairs()
     * @generated
     */
    EClass CELL_PAIRS = eINSTANCE.getCellPairs();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL_PAIRS__CELLS = eINSTANCE.getCellPairs_Cells();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.CellsImpl <em>Cells</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.CellsImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCells()
     * @generated
     */
    EClass CELLS = eINSTANCE.getCells();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.CellDefImpl <em>Cell Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.CellDefImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCellDef()
     * @generated
     */
    EClass CELL_DEF = eINSTANCE.getCellDef();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ShapeRefImpl <em>Shape Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ShapeRefImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getShapeRef()
     * @generated
     */
    EClass SHAPE_REF = eINSTANCE.getShapeRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHAPE_REF__NAME = eINSTANCE.getShapeRef_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHAPE_REF__X = eINSTANCE.getShapeRef_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHAPE_REF__Y = eINSTANCE.getShapeRef_Y();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.CellImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__X = eINSTANCE.getCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__Y = eINSTANCE.getCell_Y();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.RuleImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ACTION = eINSTANCE.getRule_Action();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ActionImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ConditionImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ConditionRuleImpl <em>Condition Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ConditionRuleImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getConditionRule()
     * @generated
     */
    EClass CONDITION_RULE = eINSTANCE.getConditionRule();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_RULE__NUMBER = eINSTANCE.getConditionRule_Number();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION_RULE__RANGE = eINSTANCE.getConditionRule_Range();

    /**
     * The meta object literal for the '<em><b>Alive</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_RULE__ALIVE = eINSTANCE.getConditionRule_Alive();

    /**
     * The meta object literal for the '<em><b>Dead</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_RULE__DEAD = eINSTANCE.getConditionRule_Dead();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.ConditionRulesImpl <em>Condition Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.ConditionRulesImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getConditionRules()
     * @generated
     */
    EClass CONDITION_RULES = eINSTANCE.getConditionRules();

    /**
     * The meta object literal for the '<em><b>Rule1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION_RULES__RULE1 = eINSTANCE.getConditionRules_Rule1();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_RULES__OPERATOR = eINSTANCE.getConditionRules_Operator();

    /**
     * The meta object literal for the '<em><b>Rule2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION_RULES__RULE2 = eINSTANCE.getConditionRules_Rule2();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.RangeImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.BoundedRangeImpl <em>Bounded Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.BoundedRangeImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoundedRange()
     * @generated
     */
    EClass BOUNDED_RANGE = eINSTANCE.getBoundedRange();

    /**
     * The meta object literal for the '<em><b>Lower Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOUNDED_RANGE__LOWER_BOUND = eINSTANCE.getBoundedRange_LowerBound();

    /**
     * The meta object literal for the '<em><b>Higher Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOUNDED_RANGE__HIGHER_BOUND = eINSTANCE.getBoundedRange_HigherBound();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.LeftUnboundedRangeImpl <em>Left Unbounded Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.LeftUnboundedRangeImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getLeftUnboundedRange()
     * @generated
     */
    EClass LEFT_UNBOUNDED_RANGE = eINSTANCE.getLeftUnboundedRange();

    /**
     * The meta object literal for the '<em><b>Lower Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT_UNBOUNDED_RANGE__LOWER_BOUND = eINSTANCE.getLeftUnboundedRange_LowerBound();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.RightUnboundedRangeImpl <em>Right Unbounded Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.RightUnboundedRangeImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getRightUnboundedRange()
     * @generated
     */
    EClass RIGHT_UNBOUNDED_RANGE = eINSTANCE.getRightUnboundedRange();

    /**
     * The meta object literal for the '<em><b>Higher Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT_UNBOUNDED_RANGE__HIGHER_BOUND = eINSTANCE.getRightUnboundedRange_HigherBound();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.GridImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__SIZE = eINSTANCE.getGrid_Size();

    /**
     * The meta object literal for the '<em><b>Parts</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__PARTS = eINSTANCE.getGrid_Parts();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.OffsetImpl <em>Offset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.OffsetImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getOffset()
     * @generated
     */
    EClass OFFSET = eINSTANCE.getOffset();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OFFSET__X = eINSTANCE.getOffset_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OFFSET__Y = eINSTANCE.getOffset_Y();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.impl.SizeImpl <em>Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.impl.SizeImpl
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getSize()
     * @generated
     */
    EClass SIZE = eINSTANCE.getSize();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__WIDTH = eINSTANCE.getSize_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE__HEIGHT = eINSTANCE.getSize_Height();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.BoolOperator <em>Bool Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.BoolOperator
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getBoolOperator()
     * @generated
     */
    EEnum BOOL_OPERATOR = eINSTANCE.getBoolOperator();

    /**
     * The meta object literal for the '{@link com.simonbaars.goLDSL.GridPart <em>Grid Part</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.goLDSL.GridPart
     * @see com.simonbaars.goLDSL.impl.GoLDSLPackageImpl#getGridPart()
     * @generated
     */
    EEnum GRID_PART = eINSTANCE.getGridPart();

  }

} //GoLDSLPackage
