/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.Grid#getSize <em>Size</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Grid#getParts <em>Parts</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' containment reference.
   * @see #setSize(Size)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getGrid_Size()
   * @model containment="true"
   * @generated
   */
  Size getSize();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.Grid#getSize <em>Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' containment reference.
   * @see #getSize()
   * @generated
   */
  void setSize(Size value);

  /**
   * Returns the value of the '<em><b>Parts</b></em>' attribute list.
   * The list contents are of type {@link com.simonbaars.goLDSL.GridPart}.
   * The literals are from the enumeration {@link com.simonbaars.goLDSL.GridPart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' attribute list.
   * @see com.simonbaars.goLDSL.GridPart
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getGrid_Parts()
   * @model unique="false"
   * @generated
   */
  EList<GridPart> getParts();

} // Grid
