/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Unbounded Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.LeftUnboundedRange#getLowerBound <em>Lower Bound</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getLeftUnboundedRange()
 * @model
 * @generated
 */
public interface LeftUnboundedRange extends Range
{
  /**
   * Returns the value of the '<em><b>Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower Bound</em>' attribute.
   * @see #setLowerBound(int)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getLeftUnboundedRange_LowerBound()
   * @model
   * @generated
   */
  int getLowerBound();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.LeftUnboundedRange#getLowerBound <em>Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower Bound</em>' attribute.
   * @see #getLowerBound()
   * @generated
   */
  void setLowerBound(int value);

} // LeftUnboundedRange
