/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objects</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getShapes <em>Shapes</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getMoreCell <em>More Cell</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getMoreCells <em>More Cells</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects()
 * @model
 * @generated
 */
public interface Objects extends EObject
{
  /**
   * Returns the value of the '<em><b>Shapes</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.ShapeRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shapes</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_Shapes()
   * @model containment="true"
   * @generated
   */
  EList<ShapeRef> getShapes();

  /**
   * Returns the value of the '<em><b>More Cell</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.CellDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Cell</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_MoreCell()
   * @model containment="true"
   * @generated
   */
  EList<CellDef> getMoreCell();

  /**
   * Returns the value of the '<em><b>More Cells</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.CellsDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More Cells</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_MoreCells()
   * @model containment="true"
   * @generated
   */
  EList<CellsDef> getMoreCells();

} // Objects
