/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objects</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getShapes <em>Shapes</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getCell <em>Cell</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getCells <em>Cells</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.Objects#getGrids <em>Grids</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects()
 * @model
 * @generated
 */
public interface Objects extends Board, Action
{
  /**
   * Returns the value of the '<em><b>Shapes</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.ShapeRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shapes</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_Shapes()
   * @model containment="true"
   * @generated
   */
  EList<ShapeRef> getShapes();

  /**
   * Returns the value of the '<em><b>Cell</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.CellDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_Cell()
   * @model containment="true"
   * @generated
   */
  EList<CellDef> getCell();

  /**
   * Returns the value of the '<em><b>Cells</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.Cells}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cells</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_Cells()
   * @model containment="true"
   * @generated
   */
  EList<Cells> getCells();

  /**
   * Returns the value of the '<em><b>Grids</b></em>' containment reference list.
   * The list contents are of type {@link com.simonbaars.goLDSL.Grid}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grids</em>' containment reference list.
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getObjects_Grids()
   * @model containment="true"
   * @generated
   */
  EList<Grid> getGrids();

} // Objects
