/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.goLDSL.ShapeDef#getName <em>Name</em>}</li>
 *   <li>{@link com.simonbaars.goLDSL.ShapeDef#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getShapeDef()
 * @model
 * @generated
 */
public interface ShapeDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getShapeDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ShapeDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference.
   * @see #setObjects(Objects)
   * @see com.simonbaars.goLDSL.GoLDSLPackage#getShapeDef_Objects()
   * @model containment="true"
   * @generated
   */
  Objects getObjects();

  /**
   * Sets the value of the '{@link com.simonbaars.goLDSL.ShapeDef#getObjects <em>Objects</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objects</em>' containment reference.
   * @see #getObjects()
   * @generated
   */
  void setObjects(Objects value);

} // ShapeDef
