/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.goLDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unbounded Range</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.simonbaars.goLDSL.GoLDSLPackage#getUnboundedRange()
 * @model
 * @generated
 */
public interface UnboundedRange extends Range
{
} // UnboundedRange
