/**
 * generated by Xtext 2.19.0
 */
package persons.tasks.ui.contentassist;

import persons.tasks.ui.contentassist.AbstractTaskDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TaskDSLProposalProvider extends AbstractTaskDSLProposalProvider {
}
