/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.parser.antlr;

import com.google.inject.Inject;
import com.simonbaars.parser.antlr.internal.InternalGoLDSLParser;
import com.simonbaars.services.GoLDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GoLDSLParser extends AbstractAntlrParser {

	@Inject
	private GoLDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGoLDSLParser createParser(XtextTokenStream stream) {
		return new InternalGoLDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DSL";
	}

	public GoLDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GoLDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
