/*
 * generated by Xtext 2.19.0
 */
package persons.tasks.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import persons.tasks.ui.internal.TasksActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TaskDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TasksActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TasksActivator activator = TasksActivator.getInstance();
		return activator != null ? activator.getInjector(TasksActivator.PERSONS_TASKS_TASKDSL) : null;
	}

}
