/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.scoping;

import com.simonbaars.scoping.AbstractGoLDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GoLDSLScopeProvider extends AbstractGoLDSLScopeProvider {
}
