/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.ui;

import com.simonbaars.ui.AbstractGoLDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GoLDSLUiModule extends AbstractGoLDSLUiModule {
  public GoLDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
